server:
  port: 8089

spring:
  application:
    name: trinity-asset
  config:
    import: nacos:trinity-asset.yaml
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: dev
      config:
        server-addr: 127.0.0.1:8848
        namespace: dev
        file-extension: yaml
        refresh-enabled: true

logging:
  level:
    com.trinity: DEBUG
