server:
  port: 8081

spring:
  application:
    name: trinity-auth
  config:
    import: nacos:trinity-auth.yaml
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: dev
      config:
        server-addr: 127.0.0.1:8848
        namespace: dev
        file-extension: yaml
        refresh-enabled: true

logging:
  level:
    com.trinity: DEBUG
